services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
      - /var/www/html/vendor
      - /var/www/html/node_modules
    env_file:
      - .env
    networks:
      - laravel_network
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
