# services:
#     app1:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         container_name: laravel_app1
#         working_dir: /var/www/html
#         volumes:
#             - .:/var/www/html:delegated
#             - /var/www/html/vendor
#             - /var/www/html/node_modules
#         env_file:
#             - .env
#         ports:
#             - "9001:9001"
#         networks:
#             - laravel_network

#     app2:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         container_name: laravel_app2
#         working_dir: /var/www/html
#         volumes:
#             - .:/var/www/html:delegated
#             - /var/www/html/vendor
#             - /var/www/html/node_modules
#         env_file:
#             - .env
#         ports:
#             - "9002:9002"
#         networks:
#             - laravel_network

#     app3:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         container_name: laravel_app3
#         working_dir: /var/www/html
#         volumes:
#             - .:/var/www/html:delegated
#             - /var/www/html/vendor
#             - /var/www/html/node_modules
#         env_file:
#             - .env
#         ports:
#             - "9003:9003"
#         networks:
#             - laravel_network
#     redis:
#         image: redis:latest
#         container_name: redis
#         ports:
#             - "6379:6379"
#         networks:
#             - laravel_network

#     redis_exporter:
#         image: oliver006/redis_exporter
#         container_name: redis_exporter
#         depends_on:
#             - redis
#         environment:
#             - REDIS_ADDR=redis:6379
#         ports:
#             - "9121:9121"
#         networks:
#             - laravel_network

#     # nginx:
#     #     image: nginx:latest
#     #     container_name: nginx
#     #     restart: unless-stopped
#     #     volumes:
#     #         - .:/var/www/html:delegated
#     #         - ./nginx:/etc/nginx/conf.d
#     #         - ./nginx/app1.conf:/etc/nginx/conf.d/app1.conf
#     #         - ./nginx/app2.conf:/etc/nginx/conf.d/app2.conf
#     #         - ./nginx/app3.conf:/etc/nginx/conf.d/app3.conf
#     #     ports:
#     #         - "8081:8081"
#     #         - "8082:8082"
#     #         - "8083:8083"
#     #     depends_on:
#     #         - app1
#     #         - app2
#     #         - app3
#     #     networks:
#     #         - laravel_network

# networks:
#     laravel_network:
#         driver: bridge

services:
    app1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app1
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:delegated
        env_file:
            - .env
        ports:
            - "9001:9000"
        networks:
            - laravel_network

    app2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app2
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:delegated
        env_file:
            - .env
        ports:
            - "9002:9000"
        networks:
            - laravel_network

    app3:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app3
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:delegated
        env_file:
            - .env
        ports:
            - "9003:9000"
        networks:
            - laravel_network

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/var/lib/redis
            - redis-pid:/var/run/redis
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        networks:
            - laravel_network

    redis_exporter:
        image: bitnami/redis-exporter:latest
        container_name: redis_exporter
        depends_on:
            - redis
        environment:
            - REDIS_ADDR=redis://redis:6379
        ports:
            - "9121:9121"
        networks:
            - laravel_network

    nginx_lb:
        image: nginx:latest
        container_name: nginx_load_balancer
        restart: unless-stopped
        ports:
            - "8080:80"
            - "8090:8090"
        volumes:
            - .:/var/www/html:delegated
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app1
            - app2
            - app3
        networks:
            - laravel_network

    lb_exporter:
        image: nginx/nginx-prometheus-exporter:latest
        container_name: lb_exporter
        depends_on:
            - nginx_lb
        command:
            - "-nginx.scrape-uri=http://nginx_lb:8090/nginx_status"
        ports:
            - "9113:9113"
        networks:
            - laravel_network

volumes:
    redis_data:
        driver: local
    redis-pid:
        driver: local

networks:
    laravel_network:
        driver: bridge
