global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "laravel_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["laravel_app:8000"]

  - job_name: "laravel_nginx"
    metrics_path: /status
    static_configs:
      - targets: ["laravel_nginx:80"]
