server {
    listen 8081;
    server_name app1.local;

    location / {
        proxy_pass http://laravel_app1:9000;  # container app1 di port 9000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
