server {
    listen 8082;
    server_name app2.local;

    location / {
        proxy_pass http://laravel_app2:9000;  # container app2 di port 9000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
