server {
    listen 8083;
    server_name app3.local;

    location / {
        proxy_pass http://laravel_app3:9000;  # container app3 di port 9000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
