# user nginx;
# worker_processes auto;
# error_log /var/log/nginx/error.log warn;
# pid /var/run/nginx.pid;

# events {
#     worker_connections 1024;
# }

# http {
#     include /etc/nginx/mime.types;
#     default_type application/octet-stream;

#     sendfile on;
#     keepalive_timeout 65;

#     include /etc/nginx/conf.d/*.conf;
# }





http {
    upstream laravel_backend {
        server laravel_app1:9000;
        server laravel_app2:9000;
        server laravel_app3:9000;
    }

    server {
        listen 80;

        location / {
            root /var/www/html/public;
            index index.php index.html;

            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass laravel_backend;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        }

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;  # Restrict access to localhost or a trusted IP
            deny all;
        }
    }
}
